// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package esi.buildit9.domain;

import esi.buildit9.domain.PlantHireRequestLine;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PlantHireRequestLine_Roo_Configurable {
    
    declare @type: PlantHireRequestLine: @Configurable;
    
}
