// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package esi.buildit9.domain;

import esi.buildit9.domain.RentIt;

privileged aspect RentIt_Roo_JavaBean {
    
    public String RentIt.getName() {
        return this.name;
    }
    
    public void RentIt.setName(String name) {
        this.name = name;
    }
    
}
