// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package esi.buildit9.domain;

import esi.buildit9.domain.Site;

privileged aspect Site_Roo_JavaBean {
    
    public String Site.getAddress() {
        return this.address;
    }
    
    public void Site.setAddress(String address) {
        this.address = address;
    }
    
}
