
package esi.buildit9.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlantSoapService", targetNamespace = "http://web.soap.rentit9.esi/", wsdlLocation = "http://localhost:8080/PlantSoapService?wsdl")
public class PlantSoapServiceService
    extends Service
{

    private final static URL PLANTSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLANTSOAPSERVICE_EXCEPTION;
    private final static QName PLANTSOAPSERVICE_QNAME = new QName("http://web.soap.rentit9.esi/", "PlantSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PlantSoapService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLANTSOAPSERVICE_WSDL_LOCATION = url;
        PLANTSOAPSERVICE_EXCEPTION = e;
    }

    public PlantSoapServiceService() {
        super(__getWsdlLocation(), PLANTSOAPSERVICE_QNAME);
    }

    public PlantSoapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLANTSOAPSERVICE_QNAME, features);
    }

    public PlantSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, PLANTSOAPSERVICE_QNAME);
    }

    public PlantSoapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLANTSOAPSERVICE_QNAME, features);
    }

    public PlantSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlantSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlantSoapService
     */
    @WebEndpoint(name = "PlantSoapServicePort")
    public PlantSoapService getPlantSoapServicePort() {
        return super.getPort(new QName("http://web.soap.rentit9.esi/", "PlantSoapServicePort"), PlantSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlantSoapService
     */
    @WebEndpoint(name = "PlantSoapServicePort")
    public PlantSoapService getPlantSoapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.soap.rentit9.esi/", "PlantSoapServicePort"), PlantSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLANTSOAPSERVICE_EXCEPTION!= null) {
            throw PLANTSOAPSERVICE_EXCEPTION;
        }
        return PLANTSOAPSERVICE_WSDL_LOCATION;
    }

}
