package esi.buildit9.interop.rentit30;

public enum POStatus {

	PENDING_CONFIRMATION, PENDING_PLANT_EXAMINATION, CLOSED, REJECTED, PLANT_REJECTED, PLANT_DELIVERED, PLANT_DISPATCHED, PLANT_RETURNED, INVOICED, PAID, CANCELLED
}
